
experiment: "baseline_final"

data:
  root: "PanopTILs_data/BootstrapNucleiManualRegions_TCGA_05132021"
  subset: "tcga"
  batch_size: 16
  num_workers: 4
  cache_dataset: true
  pin_memory: true
  persistent_workers: true

  use_weighted_sampler: true
  gamma_s: 0.95

  num_nuclei_classes: 10
  num_tissue_classes: 5
  nuclei_unlabeled_class: 0
  nuclei_background_class: 9
  nuclei_ambiguous_classes: [8]
  tissue_ignore_classes: [0]
  tissue_context_size: 512

splits:
  mode: dev
  num_val_hospitals: 5

model:
  embed_dim: 384
  depth: 12
  num_heads: 6
  extract_layers: [3, 6, 9, 12]
  encoder_pretrained: "weights/vit256_small_dino.pth"
  use_tissue_branch: false
  tissue_fusion: "none"

loss:
  lambda_np_ft: 1.0
  lambda_np_dice: 1.0

  lambda_hv_mse: 2.5
  lambda_hv_msge: 8.0

  lambda_nt_ft: 1.0
  lambda_nt_dice: 0.5
  lambda_nt_bce: 1.0

  lambda_tc_ce: 0.0

  ft_alpha: 0.4
  ft_beta: 0.6
  ft_gamma: 1.3333
  ft_eps: 1.0e-6

train:
  lr: 0.0003
  wd: 0.0001
  betas: [0.9, 0.999]

  epochs: 130

  scheduler_type: exponential
  scheduler_eta_min: 0.95

  early_stopping_patience: 15

  use_mixed_precision: true
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0

  freeze_encoder_epochs: 25

  val_metric_interval: 5
